name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run Script
      run: |
        bash build.sh

    - name: Push Branch
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        rm -rf ../out
        cp -rf out ..
        git checkout gh-pages --
        rm -rf *
        cp -rf ../out/* .
        git add --all
        git commit -m "[CI Chore] Update gh-pages"
        git push origin gh-pages